--- #YAML:1.0
name:               Task-BeLike-ALEXBIO
version:            0.02
abstract:           Useful modules list
author:
    - Alessandro Ghedini <alexbio@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    AnyEvent:             0
    AnyEvent::HTTPD:      0
    App::Ack:             0
    App::TwitShell:       0
    Compress::LZMA::External:  0
    CPAN::Mini:           0
    CPAN::SQLite:         0
    Crypt::Blowfish:      0
    Crypt::CBC:           0
    Crypt::RandPasswd:    0
    Devel::NYTProf:       0
    Devel::Trace:         0
    JSON:                 0
    JSON::XS:             0
    JSON:PP:              0
    LWP:                  0
    Media::Type::Simple:  0
    Module::CheckDeps:    0
    Module::Starter:      0
    Module::Starter::Smart:  0
    Moose:                0
    Perl::Critic:         0
    Regexp::Common:       0
    Test::More:           0
    Test::Pod:            0
    Test::Pod::Coverage:  0
    Text::Todo::Simple:   0
    WWW::GitHub::Gist:    0
    XML::Simple:          0
    YAML:                 0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
